AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  offline-development-api
  
Globals:
  Function:
    Timeout: 60

Resources:
  GetAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-all/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        GetItem:
          Type: Api
          Properties:
            Path: /user/
            Method: any
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: "false"
  GetUpdateDelete:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-all/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        GetItem:
          Type: Api
          Properties:
            Path: /user/{id}
            Method: any
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: "false"      

  GetItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-item/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        GetItem:
          Type: Api
          Properties:
            Path: /items/{itemId}
            Method: any
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: "false"
